import './globals.css'
import {Inter} from '@next/font/google';
import React from "react";

const inter = Inter()

type Props = {
    readonly children: React.ReactNode
}

export default function RootLayout({children}: Props) {

    return (
        <html lang="en" className={inter.className}>
        <head>
            <title>Christian Matschke</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </head>
        <body className={'h-screen'}>{children}</body>
        </html>
    )
}